### ISSUE TITLE
Error downloading chapter

### ISSUE THREAD

**Issue by unknown--** [frozenpandaman/mangadex-dl#1]
Series: https://mangadex.org/title/429/shingeki-no-kyojin
Chapter: 121
Error: `    chapter_num = float(manga["chapter"][chapter_id]["chapter"])
ValueError: could not convert string to float: `

**Comment by frozenpandaman** [comment]
Oops, missed this somehow. 🙃

Fixed – the script now doesn't error out when trying to download a manga with available oneshot chapters (like it was doing here; for those, the chapter number is a blank string and can't be converted into a float).

However, (for now) chapter 121 of your example won't be available to download anyway as there's no English release of it.
