### ISSUE TITLE
Error with URL

### ISSUE THREAD

**Issue by Askadelion** [frozenpandaman/mangadex-dl#10]
I have an Error at the download
http://puu.sh/FAJ89/ea8175411f.png
the error come on this title https://mangadex.org/title/19600/danberu-nan-kiro-moteru
other title running only this is a problem

**Comment by frozenpandaman** [comment]
This seems to be working for me:
![image](https://user-images.githubusercontent.com/7245874/79965894-77733100-8441-11ea-97fe-dd48caab1484.png)

I'd only expect to see that German "press any key" message if you were running the script as an executable in Command Prompt (but I'm not that familiar with Windows). How are you running the script, or what command are you using?

**Comment by Askadelion** [comment]
> I'd only expect to see that German "press any key"
this comming from batchfile if the progress of python script done show this from batch comand pause

i starting the script with a batchfile:

> @echo off & setlocal
> SET /p lang=Lang(de=German,gb=English: 
> mangadex-dl %lang%
> pause

the output command is at the end:
mangadex-dl gb

![ss (2020-04-22 at 01 43 54)](https://user-images.githubusercontent.com/41443013/79978083-99030580-849f-11ea-86f9-1317813df4a8.png)

i have only problems with this manga-title other sites run

![ss (2020-04-22 at 01 44 59)](https://user-images.githubusercontent.com/41443013/79978170-bd5ee200-849f-11ea-906b-b176e5a813e4.png)

i dont know who is the error.

**Comment by frozenpandaman** [comment]
I don't use Windows so can't test the batch file myself, but does it work without that, i.e. running `python mangadex-dl.py gb`? (gb isn't even necessary, but just in case…)

I'm guessing that's where the error's springing up, since the command above works fine for me. Maybe something with the question mark in the manga title (even though it's not in the URL or anything…?) messing up the running of the batch file? Hmm.

**Comment by matty0005** [comment]
I ran this myself on windows and fortunately got a bit more of an error log. 

An OSError is raised, specifically `OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Matt\\download\\Danberu Nan Kiro Moteru?'`

Specifically, line 129 is causing the error for me. Windows doesn't seem to like the question mark in the title.

@Askadelion, you can fix this issue by changing line 40 from `title = manga["manga"]["title"]` to `title = manga["manga"]["title"].strip("?")`

**Comment by Askadelion** [comment]
@matty0005 Thanks, this modify its perfect now its running

Error is Fixed with this 👍
