### ISSUE TITLE
Escape slashes in the series name

### ISSUE THREAD

**Issue by doroshenko** [frozenpandaman/mangadex-dl#16]
It is currently impossible to download the manga with a name that contains slash character, for example [Fate/Extra CCC Fox Tail](https://mangadex.org/title/10808/fate-extra-ccc-fox-tail).

Slash is currently being treated a part of the path by the script, which results in a subfolder creation during the download. The solution could be to substitute it for another character, i.e. dash.

**Comment by frozenpandaman** [comment]
Thanks! Fixed in a7b5cd3.
