### ISSUE TITLE
It were be fail when title include colon(special characters) on windows

### ISSUE THREAD

**Issue by ghsbyy01** [frozenpandaman/mangadex-dl#17]
for example: https://mangadex.org/title/41485/id-invaded-brake-broken

Traceback (most recent call last):
  File "mangadex-dl.py", line 161, in <module>
    dl(manga_id, lang_code, url[-1])
  File "mangadex-dl.py", line 125, in dl
    os.makedirs(dest_folder)

**Comment by frozenpandaman** [comment]
Thanks! Similar issue to #16. Fixed in 851aebf. I just had it replace all special characters:
https://github.com/frozenpandaman/mangadex-dl/blob/851aebfd89ae06707fdac734a80939e3e241103c/mangadex-dl.py#L122
