### ISSUE TITLE
Error not defined when downloading a page fails

### ISSUE THREAD

**Issue by doersino** [frozenpandaman/mangadex-dl#25]
Here, the variable `e` is not defined, which leads to an unhelpful error when a page doesn't download quite right:

https://github.com/frozenpandaman/mangadex-dl/blob/f8b7a0e5a4a792a8714dce8d3066e812ce47f9f7/mangadex-dl.py#L136

Not a big deal, but I thought I'd point it out.

(Really neat tool, by the way!)

**Comment by frozenpandaman** [comment]
thanks! :)

**Comment by doersino** [comment]
Thank *you*! :)
