### ISSUE TITLE
Fails to show chapter 100 after the MD API v2 upgrade

### ISSUE THREAD

**Issue by orbea** [frozenpandaman/mangadex-dl#28]
mangadex-dl: https://github.com/frozenpandaman/mangadex-dl/commit/08858398a30266881980570f8d4cc6829148472e
python: `3.9.0`

After chapter `100` was added to the `Kengan Omega` (https://mangadex.org/title/33538/kengan-omega) series mangadex-dl only showed up to chapter `99`.

I tried an older commit and found it still worked showing the correct number of chapters and then bisected it.
```
586faa5c9296641fca704ba82ac20e208b887616 is the first bad commit
commit 586faa5c9296641fca704ba82ac20e208b887616
Author: eli fessler <eliwf8@gmail.com>
Date:   Mon Feb 1 23:43:51 2021 -0800

    upgrade to MD API v2 (#23)

 mangadex-dl.py | 60 +++++++++++++++++++++++++++++++++++-----------------------
 1 file changed, 36 insertions(+), 24 deletions(-)
```
586faa5c9296641fca704ba82ac20e208b887616

**Comment by frozenpandaman** [comment]
Weird. Should be able to take a look this week and hopefully get this fixed! Thanks!

**Comment by orbea** [comment]
Maybe related, but sometimes it fails like this before showing the chapters.
```
$ ./mangadex-dl.py 
mangadex-dl v0.3
Enter manga URL or ID: https://mangadex.org/title/33538/kengan-omega
CloudFlare error: Expecting value: line 1 column 1 (char 0)
```
First time I saw this was testing the MD API v2 update commit the first time.

**Comment by frozenpandaman** [comment]
@orbea It seems to show up to (and past, on other titles) 100 to me:
![image](https://user-images.githubusercontent.com/7245874/110423236-8bbe1d80-8055-11eb-8961-9848933b0e0d.png)

Is this still happening for you? If not, seems it was just a bug on MD's end.

**Comment by orbea** [comment]
@frozenpandaman Yes, it seems fixed here too. MD must of fixed it for their v2 API sometime between making this issue and now. Thanks for looking, I'll close this at least until it occurs again.

**Comment by frozenpandaman** [comment]
Cool! Thanks!
