### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by goldbattle** [frozenpandaman/mangadex-dl#29]
Do you have a license for the current code (for example MIT would be a good choice)?

**Comment by frozenpandaman** [comment]
I don't! I'l think about this in the coming days. Could you let me know what led you to ask, or if it's relevant to something you wanted to do?

I am generally a fan of GPT licenses in promoting others to make their work free/libre & open-source as well, especially for projects like this. People should not be profiting from downloading (or providing a way to download) legal-gray-area manga scanlations, and MD isn't trying to do that through hosting them either, which is good – unlike a lot of other sites. (And if people want to support or show appreciation for a project itself (like this one), well, there's a sponsor button at the top, or just reach out to the creator!)

**Comment by goldbattle** [comment]
I used some of the code as the base for my project over here:
https://github.com/goldbattle/mangadex_neko_cache
I am ok with any license, just want to have one on my repository for the code that I used from here.

**Comment by frozenpandaman** [comment]
Thanks for letting me know – hope others do in the future, too! And cool project. :)

I added the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html) license.
