### ISSUE TITLE
Half-integer chapter numbers in range

### ISSUE THREAD

**Issue by kiiriisame** [frozenpandaman/mangadex-dl#3]
I frequently encounter half-integer chapter numbers that I would like to download while specifying a chapter range. Clearly, to capture any non-integer chapter in a range, the script would need to check which chapters are available before generating the list of chapters to download, but as a quick hack, simply changing
`s = list(range(r[0], r[1]+1))`
to
`s = [int(i*0.5) if (i%2==0) else i*0.5 for i in range(2*r[0], 2*r[1]+1)]`
will find and download half-integer chapters, which has been enough to cover my use cases. 

Also, thank you for having shared this script. I use it to read manga on my InkPad 3. I've written a small python script to generate CBZ-files from the output of your script.

**Comment by frozenpandaman** [comment]
Thanks @kiiriisame! For some reason my account wasn't auto-watching this repo so I never got notified of this…

You raise a good point. I frequently upload chapters when only parts are out, e.g. the first few pages of [Ichigo Mashimaro](https://mangadex.org/title/2858/ichigo-mashimaro) chapter 84 were just published, so I uploaded this as "84.1" which doesn't exactly work with your solution (though it's clever for downloading any that end in `.5`!)

I revised the script so it checks (and displays) the list of available chapters to users, and then grabs ranges based on what's available, e.g. would grab 10.1 or 10.5 or whatever as well, if present, when given a list 9-12 – not just the integers.

Glad you find the script useful! :D

>I've written a small python script to generate CBZ-files from the output of your script.

That'd be pretty cool to include here, if you'd be interested. Maybe with an optional CLI flag? Feel free to make a PR adding in the functionality, or I can look into doing it (I see your repo on your profile) if you give the A-OK.

**Comment by kiiriisame** [comment]
Thank you very much for maintaining your script. Sorry for not replying earlier.

>That'd be pretty cool to include here, if you'd be interested. 

I'm not so sure. The output of my script (one big .cbz file with all chapters in one) is well suited for the InkPad3. However, for PC users, i think separate .cbz files is the norm. If these are the only sensible possibilities, I guess it might make sense to have a cbz option that takes 3 values: do not create .cbz files / create .cbz files for each chapter / create 1 .cbz file for all chapters. Do as you wish; I'm pretty comfortable with running it as a separate script for post-processing, and it'd be more work for you to maintain.

Feel free to use any code you want from my repo: my script is so simple that I don't feel it's justified for me to take any credit for it.

Also, as a bonus, once mangadex-dl can output .cbz files, it could be used together with [KCC](https://github.com/ciromattia/kcc) to produce files for a wide range of e-readers.
