### ISSUE TITLE
HTML entity parsing in folder names

### ISSUE THREAD

**Issue by darkred3** [frozenpandaman/mangadex-dl#30]
Titles that cannot be viewed without an account don't return any chapters. How about adding cookies?

**Comment by frozenpandaman** [comment]
Seems to work for me:
![image](https://user-images.githubusercontent.com/7245874/110422788-dee3a080-8054-11eb-8d6a-c28d8c0b70cf.png)

They don't display on the site unless you flip the toggle, but the API can still see & grab 'em, it seems.

If you give me an example of a URL it doesn't work with, I can look into it.

**Comment by darkred3** [comment]
Never mind, it seems to have been a problem yesterday while MD was having major issues. It's working now!
Found a different issue though. Titles with `&` seem to be parsed incorrectly.
https://mangadex.org/title/26198/albino-witch
Output folder: `Albino &amp; Witch`

**Comment by frozenpandaman** [comment]
@darkred3 Works for me:
```
$ ./mangadex-dl.py 
mangadex-dl v0.3
Enter manga URL or ID: https://mangadex.org/title/26198/albino-witch

TITLE: Albino & Witch
Available chapters:
 1, 1, 1, 1.5, 2, 2, 3, 3.5, 4, 4.1, 4.2, 5, 6
```

Are you on Windows?

**Comment by frozenpandaman** [comment]
Thanks!
