### ISSUE TITLE
Issue when attempting to download

### ISSUE THREAD

**Issue by JJGO** [frozenpandaman/mangadex-dl#32]
I tried a couple of URLs and both failed with different errors

```shell
❯ ./mangadex-dl.py -l en
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/cade38b7-64c4-4a29-8e3c-8c283291d6c6
Please enter a valid MangaDex manga (not chapter) URL or ID.
❯ ./mangadex-dl.py -l en
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/37bf7574-641e-4665-b992-f2ba8d4652b8

TITLE: Popcorn Avatar
Error retrieving the chapters list. Did you specify a valid language code?
```

Not sure what I'm doing wrong, so any help would be appreciated

**Comment by realsontaran** [comment]
I had the same issue today. I fixed it with a simple edit. You can see at pull requests.

**Comment by JJGO** [comment]
With the patch you applied, the second one downloads, but the first one still doesn't. Moreover, for the second one it downloads the wrong TItle, it detects `Popcorn Avatar` but the link is to ` Houseki no Kuni (Minimalist Color)`

```
❯ python mangadex-dl.py
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/cade38b7-64c4-4a29-8e3c-8c283291d6c6
Please enter a valid MangaDex manga (not chapter) URL or ID.

❯ python mangadex-dl.py
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/37bf7574-641e-4665-b992-f2ba8d4652b8

TITLE: Popcorn Avatar
Available chapters:
 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29

Enter chapter(s) to download: 
```


My guess is that there is more than one bug happening here

**Comment by realsontaran** [comment]
Sorry about that. I tried with id of manga. Now I think script works as expected. Updated pull request.

**Comment by JJGO** [comment]
Tested both, and they are now working. Thanks so much for fixing it!

**Comment by denppa** [comment]
Encountered same error just now. With anything I try. Problem popped up again? 

Also just cloned the git so it is the latest.

**Comment by realsontaran** [comment]
Did you tried my fork? Because pr not merged by author yet.

**Comment by denppa** [comment]
> Did you tried my fork? Because pr not merged by author yet.

No I didn't know you had a fork. Just cloned it and did this:
```
mangadex-dl]$ python mangadex-dl.py -l en
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/80c4c4bc-be9c-400a-8cc0-57b1d0b8a87f

TITLE: Yasashii Sekai no Tsukurikata
Error retrieving the chapters list. Did you specify a valid language code?
```

**Comment by frozenpandaman** [comment]
FYI I'm traveling now but will take a look at this & all related issues/PRs shortly after I get back. :)

**Comment by realsontaran** [comment]
> ```
> mangadex-dl]$ python mangadex-dl.py -l en
> mangadex-dl v0.4.1
> Enter manga URL or ID: https://mangadex.org/title/80c4c4bc-be9c-400a-8cc0-57b1d0b8a87f
> 
> TITLE: Yasashii Sekai no Tsukurikata
> Error retrieving the chapters list. Did you specify a valid language code?
> ```
English is default language code. So If you dont give `-l en` argument it should work.

**Comment by denppa** [comment]
@realsontaran  Did you give it a try yourself before posting a possible answer here?
```
$ python mangadex-dl.py
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/80c4c4bc-be9c-400a-8cc0-57b1d0b8a87f

TITLE: Yasashii Sekai no Tsukurikata
Error retrieving the chapters list. Did you specify a valid language code?```

**Comment by realsontaran** [comment]
@Horuyuki yes I did. 
```
$ ./mangadex-dl.py 
mangadex-dl v0.4.1
Enter manga URL or ID: https://mangadex.org/title/db692d58-4b13-4174-ae8c-30c515c0689c

TITLE: Hunter x Hunter
Available chapters:
 1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11,..... 390

Enter chapter(s) to download:
```
Are you sure you are running my fork? Because it works with `-l en` as well.

**Comment by denppa** [comment]
@realsontaran  So I did just clone your fork and it worked sorry forgot to do that. And why is that? Is it because your fork is the master or this one is just not maintained anymore?

**Comment by realsontaran** [comment]
Mangadex was down. They changed the link types on their new site. Some API calls have also changed I guess. Author of the repository is traveling. My fork is just for sending pull request to main repository.

**Comment by frozenpandaman** [comment]
Thank you for the PR, @realsontaran! Merged now which should have fixed this all, I think.

MangaDex changed their URL format, e.g.
https://mangadex.org/title/311/yotsuba-to
has become
https://mangadex.org/title/58be6aa6-06cb-4ca5-bd20-f1392ce451fb
and the old way way to only detect numbers in the last part of the URL, not all characters.

If there are other changed API calls that broke anything (or break anything in the future and I don't catch it first) do let me know.
