### ISSUE TITLE
Data saver flag option?

### ISSUE THREAD

**Issue by ScherisMarie** [frozenpandaman/mangadex-dl#34]
Would it be possible to add an optional flag to fetch the **data saver** version of a chapter?

I use this script to grab the chapter images to put into a MOBI/AWZ3 archive for loading onto my Kindle, but due to the limited space on those devices I prefer to grab the data saver version.

On the old API I was able to manually edit the Python file to add `?saver=true` to do this for the `https://api.mangadex.{}/v2/chapter/{}/` call, but I'm not sure due to the changes how one would go about doing this with the new API.

Guessing this could use a `-d` flag perhaps?

**Comment by frozenpandaman** [comment]
Sure! This should be pretty easy to do. I'm traveling right now for the next week but can look into this when I get back.

**Comment by frozenpandaman** [comment]
Sorry for the delay, enjoy!
