### ISSUE TITLE
Title fails to grab if API attribute isn't EN-based

### ISSUE THREAD

**Issue by ScherisMarie** [frozenpandaman/mangadex-dl#46]
https://mangadex.org/title/bc86a871-ddc5-4e42-812a-ccd38101d82e/hana-ni-arashi

Noticed this evening that this title in particular returns `Error - could not retrieve manga title.` when using both the URL & ID parameters.

Not sure how many other(s) are affected, the script _did_ work on the last chapter so it must be something recently changed with the API.

https://api.mangadex.org/manga/bc86a871-ddc5-4e42-812a-ccd38101d82e
https://api.mangadex.org/manga/ba132c0d-68fa-4a1b-8db4-ff00caeceb55

Seems reading the script code is that it fails because `title` only returns a JA code and the EN title is under `altTitles`? As comparing it to another one that _does_ work shows `title` returns a EN code by default.

I manually altered the backup check to grab the JA address and that fixed it, but ideally it'd use the `altTitles` variable but I don't know enough Python to be able to grab it out of the nested array the API uses.

**Comment by doroshenko** [comment]
I've encountered the same problem with a different manga, the issue seems to be relatively widespread. 

My PR is available here: https://github.com/frozenpandaman/mangadex-dl/pull/47

**Comment by frozenpandaman** [comment]
Thanks @ScherisMarie! Just merged your PR, @doroshenko – appreciate you taking the time to fix this (and account for the different language codes users may have entered, too!)
