### ISSUE TITLE
Cannot download oneshots

### ISSUE THREAD

**Issue by wizhi** [frozenpandaman/mangadex-dl#5]
First off, thanks for the script, it's great and simple.

Getting this error when trying to download Fullmetal Alchemist, full output below.

```
Enter manga URL: https://mangadex.org/title/286/fullmetal-alchemist

Title: Fullmetal Alchemist
Traceback (most recent call last):
  File "./mangadex-dl.py", line 144, in <module>
    dl(manga_id, lang_code)
  File "./mangadex-dl.py", line 44, in dl
    chapters.sort(key=lambda x: float(x)) # sort numerically by chapter #
  File "./mangadex-dl.py", line 44, in <lambda>
    chapters.sort(key=lambda x: float(x)) # sort numerically by chapter #
ValueError: could not convert string to float: ''
```

I've never been any good with Python, but it seems that the API returns something which is interpreted as a string, and not a number, causing this cast to fail.

**Comment by wizhi** [comment]
Ah it's probably due to this, from [the API](https://mangadex.org/api/manga/286):

```
"chapter": {
   "129673": {
      "volume": "0",
      "chapter": "",
      "title": "Oneshot - Fullmetal Alchemist The Prototype",
      "lang_code": "gb",
      "group_id": 1236,
      "group_name": "Mangacurse",
      "group_id_2": 128,
      "group_name_2": "INP-Mangaz",
      "group_id_3": 0,
      "group_name_3": null,
      "timestamp": 1520007120
    }
}
```

Since [`chapter.<id>.chapter` is simply copied](https://github.com/frozenpandaman/mangadex-dl/blob/7e48c9010ce4c5e723c33b5d1eb9b1405b641224/mangadex-dl.py#L43), the `chapters` array will contain an empty string, which I'm guessing `float(x)` can't handle.

**Comment by frozenpandaman** [comment]
Thanks for the bug report! I was thinking this would happen for manga containing oneshots along with numbered chapters, but didn't have any titles to test it out on. :D Yup, you're right about the cause of the error. Just treating the empty strings as a "0" or something and letting them get sorted to the beginning or end of the list would be ideal, I think. Will work on a fix shortly, when I'm free!

**Comment by frozenpandaman** [comment]
@Wizhi The [`oneshot_dl` branch](https://github.com/frozenpandaman/mangadex-dl/tree/oneshot_dl) should at least allow you download the bulk of the chapters of that title for now.

But there's still no way to actually download oneshot chapters. I'll have to think a bit about the best way to make this possible (e.g. represent/list them as 0… but what if there's multiple? etc.)

**Comment by wizhi** [comment]
Thanks a bunch.

If I can find the time for it, I'll give you a pull request sometime before Christmas. :)
