### ISSUE TITLE
Unrecognized arguements

### ISSUE THREAD

**Issue by Mecha-tackz** [frozenpandaman/mangadex-dl#56]
C:\Users\user\mangadex-dl>python mangadex-dl.py [-l language_code] [-d] [-a] [-o dl_dir]
mangadex-dl v0.7
usage: mangadex-dl.py [-h] [-l LANG] [-d] [-a] [-o OUTDIR]
mangadex-dl.py: error: unrecognized arguments: [-l language_code] [-d] [-a] [-o dl_dir]

I'm on windows 10 and I have python and requests updated to the latest versions, it just refuses to work for some reason

**Comment by frozenpandaman** [comment]
Brackets are just placed around arguments to show they're optional. You need to choose which (if any) to specify and then type them without being surrounded with the `[]`.
