### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by derekneuland** [frozenpandaman/mangadex-dl#9]
First off, thank you for this script! I just installed it and am getting the following error when I try to request a title:

 ./mangadex-dl.py
mangadex-dl v0.2
Enter manga URL: https://mangadex.org/title/14405/plunderer
Traceback (most recent call last):
  File "./mangadex-dl.py", line 149, in <module>
    url = input("Enter manga URL: ").strip()
  File "<string>", line 1
    https://mangadex.org/title/14405/plunderer
         ^
SyntaxError: invalid syntax

any ideas what is causing this?

**Comment by matty0005** [comment]
Hi @derekneuland 

I tested this myself, and the url you provided works just fine.

It looks to be an issue on the python configuration on your end. What version of python are you running? This script will fail with python2. Make sure you are using python 3. 
To make sure you are using python3, use `python3 mangadex-dl.py`

**Comment by frozenpandaman** [comment]
Yep, you'll want to be using Python 3. (You can check by running `python --version`.) Do note that depending on how you've installed it, it won't necessarily will be set up to use the `python3` alias.
